[CMOB-1458]/Feature/design
DavitTsiskarashvili/Space-Quiz-App pull request #1
Opened 2023-05-17 12:08 UTC by DavitTsiskarashvili

https://spaceneobank.atlassian.net/browse/CMOB-1458

- Added basic packages
- Added start and home pages
- Added two custom views
- Added navigation using nav-graph

2023-05-23 06:35 UTC, Gio481 requested changes

2023-05-23 06:35 UTC, Gio481 commented on app/src/main/java/com/space/quiz_app/presentation/custom_view/BaseCustomView.kt
> +abstract class BaseCustomView(context: Context, attrs: AttributeSet) : View(context, attrs) {
BaseCustomView -> QuizBaseCustomView

2023-05-23 06:35 UTC, Gio481 commented on app/src/main/java/com/space/quiz_app/presentation/custom_view/CustomQuestionBackground.kt
> +class CustomQuestionBackground(
CustomQuestionBackground -> QuizCustomQuestionBackground

2023-05-23 06:35 UTC, Gio481 commented on app/src/main/java/com/space/quiz_app/presentation/custom_view/CustomQuestionBackground.kt
> +        val radius = width / 4
centerX1 რა არის ან რატო ყოფ 4 ზე ასევე centerX2 რა არის და რატო ამრავლებ სამზე მერე ოთხზე ყოფ დაუწერე კომენტარების სახით რო გასაგები იყოს კონკრეტული ხაზი რას გაძლებს და რას ემსახურება და რატო ამრავლებ აკლებ ყოფ და ასე შემდეგ

2023-05-23 06:35 UTC, Gio481 commented on app/src/main/java/com/space/quiz_app/presentation/custom_view/CustomStartBackground.kt
> +class CustomStartBackground(
StartBackground არაა შესაბამისი სახელი, გადაარქვი და Quiz თავში

2023-05-23 06:35 UTC, Gio481 commented on app/src/main/java/com/space/quiz_app/presentation/custom_view/CustomStartBackground.kt
> +        val centerY2 = height * 2 / 3 - heightDiff
იგივე აქაც დაუწერე თითო ოპერაციას კომენტარად რას აკეთებენ

2023-05-23 06:35 UTC, Gio481 commented on app/src/main/java/com/space/quiz_app/presentation/quiz_activity/QuizActivity.kt
> +
ცარიელი ხაზებია

2023-05-23 06:35 UTC, Gio481 commented on app/src/main/java/com/space/quiz_app/presentation/quiz_activity/QuizActivity.kt
> +        setUpNavigation()
ამას არ უნდა ბაინდინგი ?

2023-05-23 06:35 UTC, Gio481 commented on app/src/main/java/com/space/quiz_app/presentation/quiz_home_screen/HomeFragment.kt
> +}
ამის დაწერას რა აზრი აქვს როცა შემდეგ პრში უნდა გადაასწორო ბეიზ ფრაგმენტს რო გააკეთებ, გააკეთე ბეიზი ჯერ ორი ფუნქციით და შემდეგ პრებში ამატე ფუნქციები მაგალითად, ეს ახლა დაწერე ლიჟბი რო გეწეროს და არაა ეგრე სწორი

2023-05-23 06:35 UTC, Gio481 commented on app/src/main/java/com/space/quiz_app/presentation/quiz_start_screen/StartFragment.kt
> +class StartFragment : Fragment() {
StartFragment არაა შესაბამისი სახელი, მოიფიქრე სხვა რამე

2023-05-23 06:35 UTC, Gio481 commented on app/src/main/java/com/space/quiz_app/presentation/quiz_start_screen/StartFragment.kt
> +    private fun navigation() {
ანამ რამდენჯერ თქვა რო ფუნქციის სახელი ზმნა უნდა იყოსო და კიდე არ ითვალისწინებ მაგას ?

2023-05-23 06:35 UTC, Gio481 commented on app/src/main/java/com/space/quiz_app/presentation/quiz_start_screen/StartViewModel.kt
> +class StartViewModel : ViewModel() {
ამასაც შესაბამისად გადაარქვემ სახელს

2023-05-23 06:35 UTC, Gio481 commented on app/src/main/java/com/space/quiz_app/presentation/taken_quiz_screen/TakenQuizFragment.kt
> +class TakenQuizFragment : Fragment() {
TakenQuizFragment შეუსაბამო სახელია, გადაარქვი

2023-05-23 06:35 UTC, Gio481 commented on app/src/main/res/drawable/shape_circle.xml
> +</shape>
ეს ოვალი კანვასით არ უნდა დაიხატოს თუ რატო გაქ ეს ?

2023-05-23 06:35 UTC, Gio481 commented on app/src/main/res/layout/close_quiz_dialog.xml
> +            android:textStyle="bold"
სტილში გაუწერე /bigMyriadGeo_Bold

2023-05-23 06:35 UTC, Gio481 commented on app/src/main/res/layout/close_quiz_dialog.xml
> +            android:textStyle="bold"
აქავ იგივე

2023-05-23 06:35 UTC, Gio481 commented on app/src/main/res/layout/congrats_dialog.xml
> +            android:textStyle="bold"
აქაც იგივე

2023-05-23 06:35 UTC, Gio481 commented on app/src/main/res/layout/fragment_home.xml
> +        android:textStyle="bold"
აქაც იგივე

2023-05-23 06:35 UTC, Gio481 commented on app/src/main/res/layout/fragment_questions.xml
> +        android:textStyle="bold"
აქაც იგივე

2023-05-23 06:35 UTC, Gio481 commented on app/src/main/res/layout/fragment_taken_quiz.xml
> +        android:background="@null"
ტრანსპარენტი დაწერე ნალის მაგივრად ბექრაუნდზე

2023-05-23 06:35 UTC, Gio481 commented on app/src/main/res/layout/fragment_taken_quiz.xml
> +        android:textStyle="bold"
იგივე აქაც

2023-05-23 06:35 UTC, Gio481 commented on app/src/main/res/layout/fragment_taken_quiz.xml
> +        android:id="@+id/divider"
კოდის ფორმატირება გინდა, როგორ წესი სტილი აიდის მერე იწერება ხოლმე

2023-05-23 06:35 UTC, Gio481 commented on app/src/main/res/layout/gpa_card_view.xml
> +            android:textStyle="bold"
სტილი არ გაქ ამ ტექსტვიუზე საერთოდ და ზოგზე სხვანაგაც

2023-05-23 06:35 UTC, Gio481 commented on app/src/main/res/layout/gpa_card_view.xml
> +            app:layout_constraintEnd_toEndOf="parent"
კოდის ფორმატირება გინდა

2023-05-23 06:35 UTC, Gio481 commented on app/src/main/res/layout/question_item.xml
> +            tools:text="@tools:sample/lorem" />
მოკლედ სადაც საჭიროა შეცვალე ბოლდი :დ

2023-05-23 06:35 UTC, Gio481 commented on app/src/main/res/values/strings.xml
> +
ცარიელი ხაზებია

2023-05-23 06:45 UTC, Gio481 commented
@DavitTsiskarashvili ყველა კლასის სახელი დაიწყე Quiz ით, მაგალითად HomeFragment რო წერია ხო უნდა მიხვდეს ადამიანი რისი ჰოუმია QuizHomeFragment მიხვდება რო ქვიზის ამბავია

2023-05-23 07:57 UTC, DavitTsiskarashvili commented on app/src/main/java/com/space/quiz_app/presentation/quiz_home_screen/HomeFragment.kt
> +}
მართალი ხარ, უბრალოდ რადგან დიზაინის ბრენჩით დავიწყე ამ ბრენჩზე გაკეთებას ვარჩიე შესაფერის ბრენჩზე მექნა. ახლა მხოლოდ იმ მიზნით დავამატე რაც წერია, რომ ტელეფონზე გამეტესტა დიზაინი. ამიტომაც ამ ბრენჩზე მაგის გასწორება არ მგონია სწორი იყოს, შემდეგ ბრენჩზე გავასწორებ

2023-05-23 08:00 UTC, DavitTsiskarashvili commented on app/src/main/java/com/space/quiz_app/presentation/quiz_start_screen/StartFragment.kt
> +    private fun navigation() {
done

2023-05-23 08:00 UTC, DavitTsiskarashvili commented on app/src/main/java/com/space/quiz_app/presentation/custom_view/CustomStartBackground.kt
> +class CustomStartBackground(
done

2023-05-23 08:03 UTC, DavitTsiskarashvili commented on app/src/main/java/com/space/quiz_app/presentation/quiz_activity/QuizActivity.kt
> +
done

2023-05-23 08:03 UTC, DavitTsiskarashvili commented on app/src/main/java/com/space/quiz_app/presentation/quiz_activity/QuizActivity.kt
> +        setUpNavigation()
done

2023-05-23 08:04 UTC, DavitTsiskarashvili commented on app/src/main/java/com/space/quiz_app/presentation/quiz_start_screen/StartFragment.kt
> +class StartFragment : Fragment() {
done

2023-05-23 08:05 UTC, DavitTsiskarashvili commented on app/src/main/java/com/space/quiz_app/presentation/quiz_start_screen/StartViewModel.kt
> +class StartViewModel : ViewModel() {
done

2023-05-23 08:06 UTC, DavitTsiskarashvili commented on app/src/main/java/com/space/quiz_app/presentation/taken_quiz_screen/TakenQuizFragment.kt
> +class TakenQuizFragment : Fragment() {
done

2023-05-23 08:10 UTC, DavitTsiskarashvili commented on app/src/main/res/drawable/shape_circle.xml
> +</shape>
არა, XML-ში ვიყენებ ბათონისთვის

2023-05-23 08:20 UTC, DavitTsiskarashvili commented on app/src/main/res/layout/close_quiz_dialog.xml
> +            android:textStyle="bold"
done

2023-05-23 08:20 UTC, DavitTsiskarashvili commented on app/src/main/res/layout/close_quiz_dialog.xml
> +            android:textStyle="bold"
done

2023-05-23 08:20 UTC, DavitTsiskarashvili commented on app/src/main/res/layout/congrats_dialog.xml
> +            android:textStyle="bold"
done

2023-05-23 08:20 UTC, DavitTsiskarashvili commented on app/src/main/res/layout/fragment_home.xml
> +        android:textStyle="bold"
done

2023-05-23 08:20 UTC, DavitTsiskarashvili commented on app/src/main/res/layout/fragment_questions.xml
> +        android:textStyle="bold"
done

2023-05-23 08:22 UTC, DavitTsiskarashvili commented on app/src/main/res/layout/fragment_taken_quiz.xml
> +        android:background="@null"
done

2023-05-23 08:22 UTC, DavitTsiskarashvili commented on app/src/main/res/layout/fragment_taken_quiz.xml
> +        android:textStyle="bold"
done

2023-05-23 08:23 UTC, DavitTsiskarashvili commented on app/src/main/res/layout/fragment_taken_quiz.xml
> +        android:id="@+id/divider"
done

2023-05-23 08:26 UTC, DavitTsiskarashvili commented on app/src/main/res/layout/gpa_card_view.xml
> +            android:textStyle="bold"
done

2023-05-23 08:26 UTC, DavitTsiskarashvili commented on app/src/main/res/layout/gpa_card_view.xml
> +            app:layout_constraintEnd_toEndOf="parent"
done

2023-05-23 08:26 UTC, DavitTsiskarashvili commented on app/src/main/res/layout/question_item.xml
> +            tools:text="@tools:sample/lorem" />
done

2023-05-23 08:26 UTC, DavitTsiskarashvili commented on app/src/main/res/values/strings.xml
> +
done

2023-05-23 08:29 UTC, DavitTsiskarashvili commented
> @DavitTsiskarashvili ყველა კლასის სახელი დაიწყე Quiz ით, მაგალითად HomeFragment რო წერია ხო უნდა მიხვდეს ადამიანი რისი ჰოუმია QuizHomeFragment მიხვდება რო ქვიზის ამბავია

@Gio481 ვერ დაგეთანხმები. პროექტს ჰქვია Quiz და აპლიკაცია ამის მეტ ფუნქციას არ ასრულებს. ეს რომ უფრო კომპლექსური აპლიკაცია იყოს შინაარსობრივად ერთზე მეტი ფუნქციით, ან რაიმე ზოგადი სახელი ერქვას, საიდანაც ადამიანი ვერ მიხვდება რა შინაარსის აპლიკაციაზეა საუბარი, მაშინ სწორი იქნებოდა ეგ მიდგომა. ამ შემთხვევაში კი ნებისმიერი ფრაგმენტი რომ ქვიზისაა ცალსახაა, ყველა მიხვდება.

2023-05-23 08:29 UTC, DavitTsiskarashvili commented on app/src/main/java/com/space/quiz_app/presentation/custom_view/BaseCustomView.kt
> +abstract class BaseCustomView(context: Context, attrs: AttributeSet) : View(context, attrs) {
ზოგად კომენტარში მიგიწერე ამაზე პასუხი

2023-05-23 08:29 UTC, DavitTsiskarashvili commented on app/src/main/java/com/space/quiz_app/presentation/custom_view/CustomQuestionBackground.kt
> +class CustomQuestionBackground(
ამაზეც

2023-05-23 08:38 UTC, DavitTsiskarashvili commented on app/src/main/java/com/space/quiz_app/presentation/custom_view/CustomQuestionBackground.kt
> +        val radius = width / 4
done

2023-05-23 08:47 UTC, DavitTsiskarashvili commented on app/src/main/java/com/space/quiz_app/presentation/custom_view/CustomStartBackground.kt
> +        val centerY2 = height * 2 / 3 - heightDiff
done

2023-05-23 10:16 UTC, DavitTsiskarashvili commented on app/src/main/java/com/space/quiz_app/presentation/custom_view/BaseCustomView.kt
> +abstract class BaseCustomView(context: Context, attrs: AttributeSet) : View(context, attrs) {
done

2023-05-23 10:16 UTC, DavitTsiskarashvili commented on app/src/main/java/com/space/quiz_app/presentation/custom_view/CustomQuestionBackground.kt
> +class CustomQuestionBackground(
done

2023-05-23 10:17 UTC, DavitTsiskarashvili commented
> @DavitTsiskarashvili ყველა კლასის სახელი დაიწყე Quiz ით, მაგალითად HomeFragment რო წერია ხო უნდა მიხვდეს ადამიანი რისი ჰოუმია QuizHomeFragment მიხვდება რო ქვიზის ამბავია

done

2023-05-23 11:02 UTC, DavitTsiskarashvili commented on app/src/main/java/com/space/quiz_app/presentation/quiz_home_screen/HomeFragment.kt
> +}
done

2023-05-24 11:13 UTC, Gio481 approved these changes

2023-05-29 09:02 UTC, AnaRusadze requested changes

2023-05-29 09:02 UTC, AnaRusadze commented on app/src/main/ic_man-playstore.png
ეს წასაშლელია, არ გჭირდება

2023-05-29 09:02 UTC, AnaRusadze commented on app/src/main/java/com/space/quiz_app/presentation/custom_view/QuizLoginBackgroundView.kt
> +        val centerY2 = height * 2 / 3 - heightDiff
ის ბაგი დაფიქსე, სხვადასხვა დივაისზე სხვანაირად რომ იხატება?

2023-05-29 09:02 UTC, AnaRusadze commented on app/src/main/res/drawable-v24/shape_gpa_button.xml
> +<?xml version="1.0" encoding="utf-8"?>
გადმოიტანე drawable-v24დან drawable-ში

2023-05-29 09:02 UTC, AnaRusadze commented on app/src/main/res/drawable-v24/shape_next_button.xml
> +<?xml version="1.0" encoding="utf-8"?>
გადმოიტანე drawable-v24დან drawable-ში

2023-05-29 09:02 UTC, AnaRusadze commented on app/src/main/res/drawable-v24/shp_message_edittext.xml
> +<?xml version="1.0" encoding="utf-8"?>
გადმოიტანე drawable-v24დან drawable-ში

2023-05-29 09:02 UTC, AnaRusadze commented on app/src/main/res/drawable/ic_button.xml
> +<vector xmlns:android="http://schemas.android.com/apk/res/android"
ic_button ცოტა ზოგადი სახელია, შეგიძლია ფერით დააკონკრეტო, ic_yellow_button

2023-05-29 09:02 UTC, AnaRusadze commented on app/src/main/res/drawable/ic_man.xml
> +<vector xmlns:android="http://schemas.android.com/apk/res/android"
კაცის სურათი ესვიჯი არ უნდა იყოს, რადგან ვექტორული არაა. პიენჯით შემოიტანე

2023-05-29 09:02 UTC, AnaRusadze commented on app/src/main/res/layout/quiz_questions_fragment.xml
> +        android:layout_marginBottom="@dimen/dimen_114_dp"
android:layout_marginBottom="@dimen/dimen_114_dp" ამხელა მარჯინს არ ვწერთ ხოლმე. ძირითადად დიდი მარჯინები დინამიურია დივაისის ზომის მიხედვით

2023-05-29 09:02 UTC, AnaRusadze commented on app/src/main/res/mipmap-anydpi-v26/ic_man.xml
> +</adaptive-icon>
ეს წესით არ გჭირდება

2023-05-29 09:02 UTC, AnaRusadze commented on app/src/main/res/mipmap-anydpi-v26/ic_man_round.xml
> +</adaptive-icon>
ეს წესით არ გჭირდება

2023-05-29 09:02 UTC, AnaRusadze commented on app/src/main/res/navigation/nav_graph.xml
> +        android:id="@+id/startFragment"
სტარტ ფრაგმენტს, ჯობია აუტენტიფიკაციის ფრაგმენტი ერქვას, როგორც შემოგვთავაზეს

2023-05-29 09:02 UTC, AnaRusadze commented on app/src/main/res/values/strings.xml
> +    <string name="hello_user">გამარჯობა, </string>
ჯობია სტრინგის რესურსის ფორმატირების მეთოდი გამოიყენო, სადაც სახელის ცვლადი სტრინგშივე იქნება მოთავსებული

2023-05-29 09:02 UTC, AnaRusadze commented on app/src/main/res/values/strings.xml
> +    <string name="your_score_is">შენ დააგროვე</string>
იგივე აქაც:
გილოცავ, შენ დააგროვე %d ქულა -> გააერთიანე ყველა სიტყვა ერთ რესურსში

2023-05-29 09:02 UTC, AnaRusadze commented on app/src/main/res/mipmap-mdpi/ic_man_round.png
როგორც მივხვდი ic_man_round და ic_man საერთოდ არ გჭირდება, მხოლოდ დატოვე ic_man_foreground

2023-05-29 12:02 UTC, DavitTsiskarashvili commented on app/src/main/java/com/space/quiz_app/presentation/custom_view/QuizLoginBackgroundView.kt
> +        val centerY2 = height * 2 / 3 - heightDiff
ვერა :(

2023-05-29 12:05 UTC, DavitTsiskarashvili commented on app/src/main/res/drawable-v24/shape_gpa_button.xml
> +<?xml version="1.0" encoding="utf-8"?>
done

2023-05-29 12:05 UTC, DavitTsiskarashvili commented on app/src/main/res/drawable-v24/shape_next_button.xml
> +<?xml version="1.0" encoding="utf-8"?>
done

2023-05-29 12:06 UTC, DavitTsiskarashvili commented on app/src/main/res/drawable-v24/shp_message_edittext.xml
> +<?xml version="1.0" encoding="utf-8"?>
done

2023-05-29 12:18 UTC, DavitTsiskarashvili commented on app/src/main/res/drawable/ic_button.xml
> +<vector xmlns:android="http://schemas.android.com/apk/res/android"
done

2023-05-29 12:18 UTC, DavitTsiskarashvili commented on app/src/main/res/layout/quiz_questions_fragment.xml
> +        android:layout_marginBottom="@dimen/dimen_114_dp"
done

2023-05-29 12:18 UTC, DavitTsiskarashvili commented on app/src/main/res/navigation/nav_graph.xml
> +        android:id="@+id/startFragment"
LogIn ფრაგმენტად მაქვს გადარქმეული შემდეგ ბრენჩებზე

2023-05-29 12:18 UTC, DavitTsiskarashvili commented on app/src/main/res/mipmap-mdpi/ic_man_round.png
done

2023-05-29 12:19 UTC, DavitTsiskarashvili commented on app/src/main/res/mipmap-anydpi-v26/ic_man_round.xml
> +</adaptive-icon>
done

2023-05-29 12:27 UTC, DavitTsiskarashvili commented on app/src/main/res/mipmap-anydpi-v26/ic_man.xml
> +</adaptive-icon>
done

2023-05-29 12:27 UTC, DavitTsiskarashvili commented on app/src/main/res/values/strings.xml
> +    <string name="hello_user">გამარჯობა, </string>
done

2023-05-29 12:28 UTC, DavitTsiskarashvili commented on app/src/main/res/values/strings.xml
> +    <string name="your_score_is">შენ დააგროვე</string>
done

2023-05-29 12:30 UTC, DavitTsiskarashvili commented on app/src/main/ic_man-playstore.png
done

2023-05-30 09:31 UTC, DavitTsiskarashvili commented on app/src/main/java/com/space/quiz_app/presentation/custom_view/QuizLoginBackgroundView.kt
> +        val centerY2 = height * 2 / 3 - heightDiff
done. ტელეფონებზე გასწორდა, დესკტოპზე და უფრო დიდზე მაინც ირევა.

2023-05-31 12:00 UTC, AleksandreGalogreBaramidze approved these changes

2023-06-01 09:06 UTC, AnaRusadze approved these changes

2023-06-01 09:07 UTC, merged

2023-06-13 13:23 UTC, AleksandreGalogreBaramidze commented on app/src/main/res/drawable/shape_next_button.xml
> +    <solid android:color="@color/yellow_primary" />
It is Green @DavitTsiskarashvili