CMOB 1813 / GPA Calculation
DavitTsiskarashvili/Space-Quiz-App pull request #13
Opened 2023-07-01 17:33 UTC by DavitTsiskarashvili

https://spaceneobank.atlassian.net/browse/CMOB-1813

In this PR:
- GPA is calculated according to users scores.
- Screen orientation is set only on portrait mode.
- On home screen subject item has a start button, which didn't have a click listener. This issue is fixed.

2023-07-04 06:51 UTC, Gio481 approved these changes

2023-07-04 11:53 UTC, AnaRusadze requested changes

2023-07-04 11:53 UTC, AnaRusadze commented on app/src/main/java/com/space/quiz_app/presentation/ui/questions/view_model/QuizQuestionsViewModel.kt
> +            quizUserRepository.saveGPA(username, gpa.toFloat())
იუსქეისი გჭირდება, რომელიც დაითვლის ჯიპიეის

2023-07-05 07:51 UTC, DavitTsiskarashvili commented on app/src/main/java/com/space/quiz_app/presentation/ui/questions/view_model/QuizQuestionsViewModel.kt
> +            quizUserRepository.saveGPA(username, gpa.toFloat())
ცალკე ბრენჩს გავაკეთებ და ყველა use case-ს იქ გავუშვებ

2023-07-05 11:23 UTC, giorgimurgulia-space approved these changes

2023-07-06 06:30 UTC, AnaRusadze approved these changes

2023-07-06 06:30 UTC, merged