CMOB 1814 / Details Screen
DavitTsiskarashvili/Space-Quiz-App pull request #14
Opened 2023-07-01 19:26 UTC by DavitTsiskarashvili

https://spaceneobank.atlassian.net/browse/CMOB-1814

In this PR:
- Details screen shows every quiz the user has taken with scores

2023-07-04 06:51 UTC, Gio481 approved these changes

2023-07-04 19:52 UTC, Gio481 requested changes

2023-07-04 19:52 UTC, Gio481 commented on app/src/main/java/com/space/quiz_app/common/utils/QuizRegex.kt
> + Username should be in Georgian
format unda

2023-07-04 19:52 UTC, Gio481 commented on app/src/main/java/com/space/quiz_app/common/utils/QuizRegex.kt
>  object QuizRegex {
Quiz tu UserName

2023-07-04 19:52 UTC, Gio481 commented on app/src/main/java/com/space/quiz_app/data/local/dao/QuizQuestionsDao.kt
>      suspend fun getQuestions(subjectTitle: String): List<QuizQuestionEntity>
getQuestionsBySubject

2023-07-04 19:52 UTC, Gio481 commented on app/src/main/java/com/space/quiz_app/data/local/dao/QuizUserDao.kt
>      suspend fun getUser(username: String): QuizUserEntity
getUser gadaarqvi

2023-07-04 19:52 UTC, Gio481 commented on app/src/main/java/com/space/quiz_app/data/local/dao/QuizUserDao.kt
> +    suspend fun updateUserStatus(username: String, activeStatus: Boolean)
updateUserStatus შესაბამისი სახელი მოუფიქრე

2023-07-04 19:52 UTC, Gio481 commented on app/src/main/java/com/space/quiz_app/data/local/dao/QuizUserSubjectsDao.kt
>      suspend fun getUserSpecificSubject(username: String, quizTitle: String): QuizUserSubjectEntity?
getUserSpecificSubject რა specific subject ? :d

2023-07-05 07:40 UTC, DavitTsiskarashvili commented on app/src/main/java/com/space/quiz_app/common/utils/QuizRegex.kt
> + Username should be in Georgian
done

2023-07-05 07:41 UTC, DavitTsiskarashvili commented on app/src/main/java/com/space/quiz_app/common/utils/QuizRegex.kt
>  object QuizRegex {
done

2023-07-05 07:42 UTC, DavitTsiskarashvili commented on app/src/main/java/com/space/quiz_app/data/local/dao/QuizQuestionsDao.kt
>      suspend fun getQuestions(subjectTitle: String): List<QuizQuestionEntity>
done

2023-07-05 07:46 UTC, DavitTsiskarashvili commented on app/src/main/java/com/space/quiz_app/data/local/dao/QuizUserDao.kt
>      suspend fun getUser(username: String): QuizUserEntity
done

2023-07-05 07:47 UTC, DavitTsiskarashvili commented on app/src/main/java/com/space/quiz_app/data/local/dao/QuizUserDao.kt
> +    suspend fun updateUserStatus(username: String, activeStatus: Boolean)
done

2023-07-05 07:50 UTC, DavitTsiskarashvili commented on app/src/main/java/com/space/quiz_app/data/local/dao/QuizUserSubjectsDao.kt
>      suspend fun getUserSpecificSubject(username: String, quizTitle: String): QuizUserSubjectEntity?
done

2023-07-05 11:24 UTC, giorgimurgulia-space approved these changes

2023-07-06 11:31 UTC, bchmsl approved these changes

2023-07-06 13:10 UTC, AnaRusadze approved these changes

2023-07-06 13:10 UTC, merged