[CMOB 1522] User Validation
DavitTsiskarashvili/Space-Quiz-App pull request #3
Opened 2023-05-30 13:10 UTC by DavitTsiskarashvili

https://spaceneobank.atlassian.net/browse/CMOB-1522

Added User Validation

2023-05-31 10:17 UTC, Gio481 requested changes

2023-05-31 10:17 UTC, Gio481 commented on app/src/main/java/com/space/quiz_app/App.kt
App -> QuizApp

2023-05-31 10:17 UTC, Gio481 commented on app/src/main/java/com/space/quiz_app/common/mapper/MapperModule.kt
> +    single { QuizUserDomainModelToEntityMapper() }
DomainToEntity

2023-05-31 10:17 UTC, Gio481 commented on app/src/main/java/com/space/quiz_app/data/local/QuizUserEntity.kt
> +    val  gpa: Float
val   gpa ზედმეტი სფეისი გაქ :დ

2023-05-31 10:17 UTC, Gio481 commented on app/src/main/java/com/space/quiz_app/data/repository/QuizUserRepositoryImpl.kt
> +    private val quizUserEntityToDomainMapper: QuizUserEntityToDomainMapper
როგორც ვხედავ ერთ მაპერს იყენებ და მეორე წასაშლელი გაქვს

2023-05-31 10:17 UTC, Gio481 commented on app/src/main/java/com/space/quiz_app/presentation/quiz_gpa_screen/ui/QuizGPAFragment.kt
> +class QuizGPAFragment : QuizBaseFragment<QuizGPAViewModelQuiz>() {
QuizGPAViewModelQuiz ორი Quiz სახელში

2023-05-31 10:17 UTC, Gio481 commented on app/src/main/java/com/space/quiz_app/presentation/quiz_home_screen/ui/QuizHomeFragment.kt
> +//        }
რატოა ჩაკომენტარებული სატესტოდ თუ იყენ ლოკალურად გქონდეს და კომიტს აღარ გამოაყოლო

2023-05-31 10:17 UTC, Gio481 commented on app/src/main/java/com/space/quiz_app/presentation/quiz_home_screen/view_model/QuizHomeViewModelQuiz.kt
> +class QuizHomeViewModelQuiz : QuizBaseViewModel() {
QuizHomeViewModelQuiz  ორი Quiz  სახელში

2023-05-31 10:17 UTC, Gio481 commented on app/src/main/java/com/space/quiz_app/presentation/quiz_login_screen/ui/QuizLoginFragment.kt
> +    }
ფუნქცია გაწყვეტილია ? აკლია რაღაც თორე წერია isValidUserName რომელმაც თრუ ან ფოლსი უნდა დაგიბრუნოს ხო და მაგის მიხედვით გაკეთდეს რაღაც

2023-05-31 10:17 UTC, Gio481 commented on app/src/main/java/com/space/quiz_app/presentation/quiz_login_screen/ui/QuizLoginFragment.kt
> +            viewModel.isValidUsername(binding.usernameEditText.text.toString())
with(binding)

2023-05-31 10:17 UTC, Gio481 commented on app/src/main/java/com/space/quiz_app/presentation/quiz_login_screen/ui/QuizLoginFragment.kt
> +                }
ექსთენშენი გააკეთე

2023-05-31 10:17 UTC, Gio481 commented on app/src/main/java/com/space/quiz_app/presentation/quiz_login_screen/view_model/QuizLoginViewModel.kt
> +    }
არასწორი სახელი არქმევია ფუნქციას, ასევე ერორ ცვლადი საქსეს როგორ უნდა უდრიდეს :დ

2023-05-31 10:17 UTC, Gio481 commented on app/src/main/java/com/space/quiz_app/presentation/quiz_login_screen/view_model/QuizLoginViewModel.kt
> +        }
ფაბლიქ ფუნქციები პრივსატულების მაღლა უნდა იყვნენ

2023-05-31 10:17 UTC, Gio481 commented on app/src/main/java/com/space/quiz_app/presentation/quiz_login_screen/view_model/QuizLoginViewModel.kt
> +        viewModelScope.launch {
viewModelScopre.launch ექსთენშენი გააკეთე და აქ ბაზებთან დაკავშირებული ფუქნცია რო გაქ რომელ თრედში უნდა გაუშვა, რომელი დისპეჩერი უნდა გამოიყენო ეგ უნდა გაუწერო

2023-05-31 10:17 UTC, Gio481 commented on app/src/main/java/com/space/quiz_app/presentation/quiz_questions_screen/view_model/QuizQuestionsViewModelQuiz.kt
> +class QuizQuestionsViewModelQuiz : QuizBaseViewModel() {
ორი Quiz სახელში

2023-05-31 10:17 UTC, Gio481 commented on app/src/main/java/com/space/quiz_app/presentation/utils/Event.kt
> +package com.space.quiz_app.presentation.utils
თავისი ფექიჯი გაუკეთე ივენთს უფრო სწორი იქნება და სახელი QuizEvent

2023-05-31 10:17 UTC, Gio481 commented on app/src/main/java/com/space/quiz_app/presentation/utils/Regex.kt
> +object Regex {
QuizRegex

2023-05-31 10:17 UTC, Gio481 commented on app/src/main/java/com/space/quiz_app/presentation/utils/Regex.kt
> +    val pattern = "^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d).{8,}$".toRegex()
რისი პატერნია

2023-05-31 10:17 UTC, Gio481 commented on app/src/main/java/com/space/quiz_app/presentation/utils/Event.kt
> +    fun peekContent(): T = content
ამის მუღამი რა არის

2023-05-31 10:17 UTC, Gio481 commented on app/src/main/java/com/space/quiz_app/presentation/utils/Validation.kt
> +enum class Validation(@StringRes val errorText: Int)  {
QuizValidation

2023-05-31 10:17 UTC, Gio481 commented on app/src/main/res/layout/quiz_login_fragment.xml
> +        android:layout_marginBottom="180dp"
ჰარდად წერია

2023-05-31 10:17 UTC, Gio481 commented on app/src/main/res/layout/quiz_login_fragment.xml
>          android:paddingEnd="@dimen/dimen_30_dp"
პადინგ ჰორიზონტალ

2023-05-31 10:17 UTC, Gio481 commented on app/src/main/res/navigation/nav_graph.xml
> +        android:name="com.space.quiz_app.presentation.quiz_login_screen.ui.QuizLoginFragment"
აიდებში დარწმუნებული ხარ ? quizLoginFragment და ასე შემდეგ ხო არ უნდა იყოს ?

2023-05-31 10:17 UTC, Gio481 commented on app/src/main/res/drawable/ic_yellow_button.xml
ic_yellow_button არაა შესაბამისი სახელი

2023-05-31 10:17 UTC, Gio481 commented on app/src/main/res/drawable/shp_message_edittext.xml
ამაზე shp გიწერია სხვებზე shape და რა შეიპებს უკეთებ ვერ ვხვდები, 20 კომპონონეტი რო გქონდეს 20 შეიპი უნდა დაგჭირდეს თუ რას ეხება ეს შეიპები ?

2023-05-31 10:17 UTC, Gio481 commented on app/src/main/res/drawable/shp_message_edittext.xml
ამაზე shp გიწერია სხვებზე shape და რა შეიპებს უკეთებ ვერ ვხვდები, 20 კომპონონეტი რო გქონდეს 20 შეიპი უნდა დაგჭირდეს თუ რას ეხება ეს შეიპები ?

2023-05-31 10:21 UTC, Gio481 commented
პრს სახელში ჯირას ნომერი დიდი ასოებით, CMOB-1522

2023-05-31 11:43 UTC, AleksandreGalogreBaramidze approved these changes

2023-06-01 07:06 UTC, DavitTsiskarashvili commented on app/src/main/java/com/space/quiz_app/App.kt
done

2023-06-01 07:13 UTC, DavitTsiskarashvili commented on app/src/main/java/com/space/quiz_app/common/mapper/MapperModule.kt
> +    single { QuizUserDomainModelToEntityMapper() }
done

2023-06-01 07:14 UTC, DavitTsiskarashvili commented on app/src/main/java/com/space/quiz_app/data/local/QuizUserEntity.kt
> +    val  gpa: Float
done

2023-06-01 07:14 UTC, DavitTsiskarashvili commented on app/src/main/java/com/space/quiz_app/data/repository/QuizUserRepositoryImpl.kt
> +    private val quizUserEntityToDomainMapper: QuizUserEntityToDomainMapper
done

2023-06-01 07:16 UTC, DavitTsiskarashvili commented on app/src/main/java/com/space/quiz_app/presentation/quiz_gpa_screen/ui/QuizGPAFragment.kt
> +class QuizGPAFragment : QuizBaseFragment<QuizGPAViewModelQuiz>() {
done

2023-06-01 07:16 UTC, DavitTsiskarashvili commented on app/src/main/java/com/space/quiz_app/presentation/quiz_home_screen/ui/QuizHomeFragment.kt
> +//        }
კარგი

2023-06-01 07:16 UTC, DavitTsiskarashvili commented on app/src/main/java/com/space/quiz_app/presentation/quiz_home_screen/view_model/QuizHomeViewModelQuiz.kt
> +class QuizHomeViewModelQuiz : QuizBaseViewModel() {
done

2023-06-01 07:19 UTC, DavitTsiskarashvili commented on app/src/main/java/com/space/quiz_app/presentation/quiz_login_screen/ui/QuizLoginFragment.kt
> +    }
არ არის გაწყვეტილი, ვიუმოდელშია ლოგიკა გატანილი. ვალიდურობის შემოწმებას რომ იძახებს, მიაკითხავს ვიუ მოდელს, თუ თრუ დაბრუნდა ვიუ მოდელშივე გამოიძახებს ბაზაში ჩასმის ფუნქციას და შემდეგ ნავიგაციის ფუნქციასაც.

2023-06-01 08:02 UTC, DavitTsiskarashvili commented on app/src/main/java/com/space/quiz_app/presentation/quiz_login_screen/ui/QuizLoginFragment.kt
> +            viewModel.isValidUsername(binding.usernameEditText.text.toString())
done

2023-06-01 08:06 UTC, DavitTsiskarashvili commented on app/src/main/java/com/space/quiz_app/presentation/quiz_login_screen/view_model/QuizLoginViewModel.kt
> +    }
done

2023-06-01 08:07 UTC, DavitTsiskarashvili commented on app/src/main/java/com/space/quiz_app/presentation/quiz_login_screen/view_model/QuizLoginViewModel.kt
> +        }
done

2023-06-01 08:31 UTC, DavitTsiskarashvili commented on app/src/main/java/com/space/quiz_app/presentation/quiz_login_screen/view_model/QuizLoginViewModel.kt
> +        viewModelScope.launch {
done

2023-06-01 08:31 UTC, DavitTsiskarashvili commented on app/src/main/java/com/space/quiz_app/presentation/quiz_questions_screen/view_model/QuizQuestionsViewModelQuiz.kt
> +class QuizQuestionsViewModelQuiz : QuizBaseViewModel() {
done

2023-06-01 08:35 UTC, DavitTsiskarashvili commented on app/src/main/java/com/space/quiz_app/presentation/utils/Regex.kt
> +object Regex {
done

2023-06-01 08:35 UTC, DavitTsiskarashvili commented on app/src/main/java/com/space/quiz_app/presentation/utils/Event.kt
> +package com.space.quiz_app.presentation.utils
done

2023-06-01 08:36 UTC, DavitTsiskarashvili commented on app/src/main/java/com/space/quiz_app/presentation/utils/Regex.kt
> +    val pattern = "^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d).{8,}$".toRegex()
done

2023-06-01 08:36 UTC, DavitTsiskarashvili commented on app/src/main/java/com/space/quiz_app/presentation/utils/Validation.kt
> +enum class Validation(@StringRes val errorText: Int)  {
done

2023-06-01 08:40 UTC, DavitTsiskarashvili commented on app/src/main/res/layout/quiz_login_fragment.xml
> +        android:layout_marginBottom="180dp"
done

2023-06-01 08:41 UTC, DavitTsiskarashvili commented on app/src/main/res/layout/quiz_login_fragment.xml
>          android:paddingEnd="@dimen/dimen_30_dp"
done

2023-06-01 08:44 UTC, DavitTsiskarashvili commented on app/src/main/res/navigation/nav_graph.xml
> +        android:name="com.space.quiz_app.presentation.quiz_login_screen.ui.QuizLoginFragment"
done

2023-06-01 08:45 UTC, DavitTsiskarashvili commented on app/src/main/res/drawable/ic_yellow_button.xml
done

2023-06-01 09:02 UTC, Gio481 commented on app/src/main/java/com/space/quiz_app/presentation/quiz_login_screen/ui/QuizLoginFragment.kt
> +    }
ხოდა სახელია არასწორი  ფუნქციის მაშინ, როგორც წესი is ით იწყება ის რაც ბულიანს გიბრუნებს

2023-06-01 09:04 UTC, DavitTsiskarashvili commented on app/src/main/java/com/space/quiz_app/presentation/quiz_login_screen/ui/QuizLoginFragment.kt
> +                }
done

2023-06-01 09:05 UTC, DavitTsiskarashvili commented on app/src/main/java/com/space/quiz_app/presentation/quiz_login_screen/ui/QuizLoginFragment.kt
> +    }
გავასწორე სახელიც. დავაკომიტებ ცოტახანში

2023-06-01 09:06 UTC, DavitTsiskarashvili commented on app/src/main/res/drawable/shp_message_edittext.xml
done. ზედმეტი shape-ები წავშალე და ღილაკებზე material buttons გამოვიყენე, შესაბამისად პარამეტრებად გავუწერე ფერი და რადიუსი (შეიფებში მეტს არაფერს ვიყენებდი)

2023-06-01 09:07 UTC, DavitTsiskarashvili commented on app/src/main/res/drawable/shp_message_edittext.xml
done

2023-06-01 09:08 UTC, DavitTsiskarashvili commented
> პრს სახელში ჯირას ნომერი დიდი ასოებით, CMOB-1522

done

2023-06-01 09:23 UTC, DavitTsiskarashvili commented on app/src/main/java/com/space/quiz_app/presentation/utils/Event.kt
> +    fun peekContent(): T = content
როგორც დავარისერჩე, ვიუმოდელიდან ნავიგაციის ქონსამფშენი ერთხელ უნდა მოხდეს, რომ კონფიგურაციის ცვლილებისას ახლიდან არ გამოისროლოს ივენთი. ამიტომ ვრეპერ კლასში ვახვევთ, რაც ერთჯერად ქონსუმფშენს უზრუნველყოფს.

2023-06-02 10:02 UTC, Gio481 requested changes

2023-06-02 10:02 UTC, Gio481 commented on app/src/main/java/com/space/quiz_app/common/extensions/ViewModelExtension.kt
> +}
რომელ დისპეჩერზე უშვებ უნდა განსაზღვრო

2023-06-02 10:02 UTC, Gio481 commented on app/src/main/java/com/space/quiz_app/common/mapper/MapperModule.kt
> +}
მაპერ მოდული ქომონში რატოა

2023-06-02 10:02 UTC, Gio481 commented on app/src/main/java/com/space/quiz_app/data/local/QuizUserDao.kt
> +    suspend fun insertUser(username: QuizUserEntity)
user უფრო შესაბამისი სახელია პარამეტრზე

2023-06-02 10:02 UTC, Gio481 commented on app/src/main/java/com/space/quiz_app/data/mapper/QuizUserDomainToEntityMapper.kt
> +
ცარიელი ხაზები

2023-06-02 10:02 UTC, Gio481 commented on app/src/main/java/com/space/quiz_app/data/repository/QuizUserRepositoryImpl.kt
> +
ცარიელი ხაზები

2023-06-02 12:13 UTC, DavitTsiskarashvili commented on app/src/main/java/com/space/quiz_app/common/extensions/ViewModelExtension.kt
> +}
done

2023-06-02 12:16 UTC, DavitTsiskarashvili commented on app/src/main/java/com/space/quiz_app/data/local/QuizUserDao.kt
> +    suspend fun insertUser(username: QuizUserEntity)
done

2023-06-02 12:17 UTC, DavitTsiskarashvili commented on app/src/main/java/com/space/quiz_app/data/mapper/QuizUserDomainToEntityMapper.kt
> +
done

2023-06-02 12:17 UTC, DavitTsiskarashvili commented on app/src/main/java/com/space/quiz_app/data/repository/QuizUserRepositoryImpl.kt
> +
done

2023-06-02 12:21 UTC, DavitTsiskarashvili commented on app/src/main/java/com/space/quiz_app/common/mapper/MapperModule.kt
> +}
done

2023-06-02 18:31 UTC, Gio481 approved these changes

2023-06-05 08:02 UTC, bchmsl approved these changes

2023-06-05 08:02 UTC, bchmsl commented on app/src/main/java/com/space/quiz_app/data/local/QuizUserDao.kt
> -    @Query("SELECT * FROM User_table")
table-ს სახელში ერთნაირი naming convention გამოიყენე, ან Capitalized, ან snake (table-სთვის რომელი სჯობს ბიჭები უფრო კარგად გვირჩევენ ;დ)

2023-06-05 08:02 UTC, bchmsl commented on app/src/main/java/com/space/quiz_app/presentation/mapper/QuizUserDomainToUIMapper.kt
> +
extra line

2023-06-05 08:02 UTC, bchmsl commented on app/src/main/java/com/space/quiz_app/presentation/utils/QuizUsernameValidation.kt
> +                input.length > 20 -> USERNAME_INVALID_LENGTH_LONG
ცვლადებად გაიტანე length

2023-06-05 08:02 UTC, bchmsl commented on app/src/main/res/layout/quiz_congrats_dialog.xml
>              style="@style/bigMyriadGeo_Regular"
big რაღაცნაირი სახელია, large გამოიყენე

2023-06-05 08:02 UTC, bchmsl commented on app/src/main/res/layout/quiz_questions_fragment.xml
> +        tools:itemCount="4"
tools-ები ბოლოში უნდა ეწეროს,
ctrl + alt + L

2023-06-05 08:02 UTC, bchmsl commented on app/src/main/res/values/text_style.xml
>      <style name="bigMyriadGeo_Bold" >
ზევით რაც დაგიწერე, big > large

2023-06-05 09:40 UTC, DavitTsiskarashvili commented on app/src/main/java/com/space/quiz_app/data/local/QuizUserDao.kt
> -    @Query("SELECT * FROM User_table")
done

2023-06-05 09:40 UTC, DavitTsiskarashvili commented on app/src/main/java/com/space/quiz_app/presentation/mapper/QuizUserDomainToUIMapper.kt
> +
done

2023-06-05 09:50 UTC, DavitTsiskarashvili commented on app/src/main/java/com/space/quiz_app/presentation/utils/QuizUsernameValidation.kt
> +                input.length > 20 -> USERNAME_INVALID_LENGTH_LONG
done

2023-06-05 09:53 UTC, DavitTsiskarashvili commented on app/src/main/res/layout/quiz_congrats_dialog.xml
>              style="@style/bigMyriadGeo_Regular"
done

2023-06-05 09:54 UTC, DavitTsiskarashvili commented on app/src/main/res/layout/quiz_questions_fragment.xml
> +        tools:itemCount="4"
done

2023-06-05 09:54 UTC, DavitTsiskarashvili commented on app/src/main/res/values/text_style.xml
>      <style name="bigMyriadGeo_Bold" >
done

2023-06-06 12:03 UTC, AleksandreGalogreBaramidze approved these changes

2023-06-07 07:28 UTC, bchmsl approved these changes

2023-06-07 07:40 UTC, merged