[CMOB1525] User Data
DavitTsiskarashvili/Space-Quiz-App pull request #5
Opened 2023-06-02 09:56 UTC by DavitTsiskarashvili

https://spaceneobank.atlassian.net/browse/CMOB-1703

Home page retrieves username after registration/login

2023-06-06 11:55 UTC, AleksandreGalogreBaramidze approved these changes

2023-06-06 11:55 UTC, AleksandreGalogreBaramidze commented on app/src/main/java/com/space/quiz_app/data/local/QuizUserEntity.kt
> +    val  gpa: Float,
Remove extra space

2023-06-06 11:55 UTC, AleksandreGalogreBaramidze commented on app/src/main/java/com/space/quiz_app/data/repository/QuizUserRepositoryImpl.kt
> +                Log.d("bachi", userEntity.toString())
Remove extra code

2023-06-07 07:30 UTC, Gio481 requested changes

2023-06-07 07:30 UTC, Gio481 commented on app/src/main/java/com/space/quiz_app/data/local/QuizUserDao.kt
> +    suspend fun getEntityIfLoggedIn(): List<QuizUserEntity>
ამას რო რეპოზიტორში მაპავ ისევ ენთითი გამოდის ?

2023-06-07 07:30 UTC, Gio481 commented on app/src/main/java/com/space/quiz_app/data/local/QuizUserDao.kt
> +    suspend fun getEntityIfLoggedIn(): List<QuizUserEntity>
რატო აბრუნებს ამათ ლისტს

2023-06-07 07:30 UTC, Gio481 commented on app/src/main/java/com/space/quiz_app/data/local/QuizUserDao.kt
> +
ზედმეტი ხაზები

2023-06-07 07:30 UTC, Gio481 commented on app/src/main/java/com/space/quiz_app/data/local/QuizUserDao.kt
> +    suspend fun getEntity(username: String): List<QuizUserEntity>
ერთი იუზერ ნეიმით მარტო ერთი ტიპი უნდა გყავდეს და ლისტი არ წამოვა

2023-06-07 07:30 UTC, Gio481 commented on app/src/main/java/com/space/quiz_app/data/mapper/QuizUserEntityToDomainMapper.kt
>              QuizUserDomainModel(
QuizUserDomain

2023-06-07 07:30 UTC, Gio481 commented on app/src/main/java/com/space/quiz_app/data/module/DatastoreModule.kt
> +    single<QuizUsernameDatastoreRepository> {QuizUsernameRepositoryImpl(get())}
ფორმატი უნდა

2023-06-07 07:30 UTC, Gio481 commented on app/src/main/java/com/space/quiz_app/data/repository/QuizUserRepositoryImpl.kt
> +    private val quizUserEntityToDomainMapper: QuizUserEntityToDomainMapper
ცვალდებს რამხელა სახელები ქვია და მაპერის სახელებიც რასაც მაპავ ის ერქვას

2023-06-07 07:30 UTC, Gio481 commented on app/src/main/java/com/space/quiz_app/data/local/QuizUserDao.kt
> +    suspend fun getEntity(username: String): List<QuizUserEntity>
ამას რო გადამაპავ მერე ენთითი ხო არ იქნება :დ ცუდი სახელებია ფუნქციებზე

2023-06-07 07:30 UTC, Gio481 commented on app/src/main/java/com/space/quiz_app/presentation/base/adapter/BaseAdapter.kt
> +}
ამის არსებობას რა აზრი აქვს პროექტში

2023-06-07 07:30 UTC, Gio481 commented on app/src/main/java/com/space/quiz_app/presentation/quiz_home_screen/ui/QuizHomeFragment.kt
>  //        }
რატოა ჩაკომენტარებული, რაღაც მახსოვს ამასთან დაკავშირებით დაგიწერე უკვე კომენტარი და კიდე მიწევს თუ რახდება, ავირიე

2023-06-07 07:30 UTC, Gio481 commented on app/src/main/java/com/space/quiz_app/presentation/quiz_home_screen/ui/QuizHomeFragment.kt
> +        }
with(binding) აღარ გინდა

2023-06-07 07:30 UTC, Gio481 commented on app/src/main/java/com/space/quiz_app/presentation/quiz_home_screen/ui/QuizHomeFragment.kt
> +        viewLifecycleOwner.lifecycleScope.launch {
ექსთენშენი გააკეთე კარგად

2023-06-07 07:30 UTC, Gio481 commented on app/src/main/java/com/space/quiz_app/presentation/quiz_home_screen/view_model/QuizHomeViewModel.kt
> +        viewModelScope.launch {
ექსთენშენი ხო გაქ ამის და აქაც გამოიყენე ბარემ

2023-06-07 07:30 UTC, Gio481 commented on app/src/main/java/com/space/quiz_app/presentation/quiz_home_screen/view_model/QuizHomeViewModel.kt
> +                Log.d("bagi", it.toString())
პრს ისე უშვებ არ უკვირდები რეები გიწერია ?

2023-06-07 07:30 UTC, Gio481 commented on app/src/main/java/com/space/quiz_app/presentation/quiz_login_screen/view_model/QuizLoginViewModel.kt
> +        }
ოპტიმიზაცია ფუნქციებში ცუდი არ იქნება

2023-06-07 10:15 UTC, DavitTsiskarashvili commented on app/src/main/java/com/space/quiz_app/presentation/base/adapter/BaseAdapter.kt
> +}
ფაილები წინასწარ გავიმზადე რაც შემდეგ დამჭირდებოდა. განვლილი ქვიზების გვერდზეც გამომადგება

2023-06-07 10:15 UTC, DavitTsiskarashvili commented on app/src/main/java/com/space/quiz_app/presentation/quiz_home_screen/ui/QuizHomeFragment.kt
>  //        }
შენ კი არა მეც ავირიე. მეც მახსოვს რომ დამიწერე და მახსოვს რომ გავასწორე :D

2023-06-07 10:16 UTC, DavitTsiskarashvili commented on app/src/main/java/com/space/quiz_app/presentation/quiz_home_screen/ui/QuizHomeFragment.kt
> +        }
done

2023-06-07 10:20 UTC, DavitTsiskarashvili commented on app/src/main/java/com/space/quiz_app/presentation/quiz_home_screen/view_model/QuizHomeViewModel.kt
> +        viewModelScope.launch {
done

2023-06-07 10:20 UTC, DavitTsiskarashvili commented on app/src/main/java/com/space/quiz_app/presentation/quiz_home_screen/view_model/QuizHomeViewModel.kt
> +                Log.d("bagi", it.toString())
my bad

2023-06-07 10:22 UTC, DavitTsiskarashvili commented on app/src/main/java/com/space/quiz_app/data/local/QuizUserDao.kt
> +    suspend fun getEntityIfLoggedIn(): List<QuizUserEntity>
არა, QuizUserDomainModel-ის Flow

2023-06-07 10:24 UTC, DavitTsiskarashvili commented on app/src/main/java/com/space/quiz_app/data/local/QuizUserDao.kt
> +
done

2023-06-07 10:24 UTC, DavitTsiskarashvili commented on app/src/main/java/com/space/quiz_app/data/mapper/QuizUserEntityToDomainMapper.kt
>              QuizUserDomainModel(
Model-ით ჩემთვის უფრო გასაგებია

2023-06-07 10:25 UTC, DavitTsiskarashvili commented on app/src/main/java/com/space/quiz_app/data/module/DatastoreModule.kt
> +    single<QuizUsernameDatastoreRepository> {QuizUsernameRepositoryImpl(get())}
done

2023-06-07 10:26 UTC, DavitTsiskarashvili commented on app/src/main/java/com/space/quiz_app/data/repository/QuizUserRepositoryImpl.kt
> +    private val quizUserEntityToDomainMapper: QuizUserEntityToDomainMapper
done

2023-06-07 10:27 UTC, DavitTsiskarashvili commented on app/src/main/java/com/space/quiz_app/data/local/QuizUserDao.kt
> +    suspend fun getEntity(username: String): List<QuizUserEntity>
done

2023-06-07 10:27 UTC, DavitTsiskarashvili commented on app/src/main/java/com/space/quiz_app/presentation/quiz_login_screen/view_model/QuizLoginViewModel.kt
> +        }
okay

2023-06-07 10:28 UTC, DavitTsiskarashvili commented on app/src/main/java/com/space/quiz_app/presentation/quiz_home_screen/ui/QuizHomeFragment.kt
> +        viewLifecycleOwner.lifecycleScope.launch {
done

2023-06-07 10:30 UTC, DavitTsiskarashvili commented on app/src/main/java/com/space/quiz_app/data/local/QuizUserDao.kt
> +    suspend fun getEntity(username: String): List<QuizUserEntity>
done

2023-06-07 10:30 UTC, DavitTsiskarashvili commented on app/src/main/java/com/space/quiz_app/data/local/QuizUserDao.kt
> +    suspend fun getEntityIfLoggedIn(): List<QuizUserEntity>
გავასწორე და ენთითის ვაბრუნებინებ

2023-06-07 11:19 UTC, Gio481 commented
@DavitTsiskarashvili როცა გასწორებულ კომენტარებს აფუშაც დანიც მაშინ დაწერე ადამიანო, თან კონფლიქტები გაქ აქ გასასწორებელი :დ

2023-06-07 11:20 UTC, Gio481 commented on app/src/main/java/com/space/quiz_app/data/local/QuizUserDao.kt
> +    suspend fun getEntityIfLoggedIn(): List<QuizUserEntity>
ხოდა მაგას ვამბობ რო სახელი გადაარქვა ამ ფუქნციას :დ

2023-06-07 12:19 UTC, closed without merging